[test]
keywords = ["test"]
content = """
tags are  working fine!
"""

[clientmissingintents]
keywords = ["cmi", "intents"]
content = """
Error `[CLIENT_MISSING_INTENTS]`
Fix:
Discord.js v13 requires you to add intents to the client
```diff
- const client = new Discord.Client()
- const client = new Discord.Client({ ws: { intents: 32767 } })

+ const client = new Discord.Client({ intents: 32767 })
```
"""

[notworking]
keywords = ["nw", "dnw"]
content = """
When someone asks a question about a problem with their code, we need to know what's wrong with it. Stating “it's not working” is not helpful.
Please give us the full description of the problem, which should include the following:
  • what needs to be accomplished
  • what has been tried already (including relevant code!)
  • a description of what the code did
  • an explanation of why this behavior does not achieve the goal
"""

[rule2]
keywords = ["r2"]
content = """
Rule 2. We expect you to have a solid understanding of JavaScript. Do not ask general questions here. There is a countless number of exceptional online resources at your disposal. We can usually point you in the right direction, but don't expect us to teach you the fundamentals from scratch. 
"""

[rule4]
keywords = ["r4"]
content = """
4. When asking for help, make sure to provide as much detail as possible. Simply saying, "it's broke yo", or "how 2 make music bot" certainly won't get either of us anywhere.
"""

[rule5]
keywords = ["r5"]
content = """
5. Don't expect us to hold your hand entirely. We can help you understand concepts and locate the correct resources, but not write your code for you.
"""

[rule6]
keywords = ["r6"]
content = """
6. Do not mention or DM individual members just for help. You may not get a reply quickly, if at all. Post your question in the public channels where more people can see it.
"""

[rule13]
keywords = ["r13"]
content = """
13. No crossposting in #『📗』help-1 and #『📕』help-2 
"""

[AbortController]
keywords = ["ac", "abort", "controller"]
content= """
**⚙️ Abort Controller /unexpected token '?'  (node version)**
• `ReferenceError: AbortController is not defined`
• `SyntaxError: Unexpected token '?' at node_modules/discord.js/src/rest/RESTManager.js:32`
• Discord.js v13 requires Node.js version 16.6 or newer to run!
• If you run your bot through a process manager, make sure to restart the daemon process to use the new node version
• Unsure you are using the right one? Log `console.log(process.version)` in your code
"""

[of-undefined]
keywords = ["undefined", "of undefined"]
content = """
`TypeError: Cannot read property 'bar' of undefined`
The variable you're trying to access the property `bar` of is undefined, not `bar` itself! | `foo.bar` - `foo`'s value is undefined.
The stack trace points exactly to the line the error occurs on.
For more information: <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_property>
"""

[application-commands]
keywords = ["application commands", "missing access"]
content = """
• `DiscordAPIError: Missing Access when trying to register slash commands`
• Enable the applications.commands scope for your bot in oauth
• You can also generate an invite by doing `console.log(<Client>.generateInvite({ scopes: ['applications.commands'] }))`
"""

[OptionsArray]
keywords = ["options.array"]
content = """
`interaction.options.array()` is not a function anymore. 
Replace `array()` with data. Do not put `()` around it, as it is a property and not a function
Read more about CommandInteractionOptionResolver#data [here](https://discord.js.org/#/docs/main/stable/class/CommandInteractionOptionResolver?scrollTo=data)
"""

[tias]
keywords = ["tias", "try it and see"]
content = """
https://tryitands.ee
"""

[External-Sources]
keywords = ["external"]
content = """
**🚫 External Sources**
We can't help with external *npm packages*, *command handlers*, *event handlers*. Some examples, we are not providing support for *discord-buttons* as there is a video already about it to learn more about it use `v13` tag, different command handlers is just a waste of time to provide support for especially when you don't quite understand what the handler is doing
"""

[version13]
keywords = ["v13"]
content = """
We are not providing support for external npm packages, here are some useful links u can learn from.
• [#1 Slash Commands](<https://www.youtube.com/watch?v=o6YWbnvncQE&t=3s>)
• [#2 Slash Commands (full)](<https://www.youtube.com/watch?v=EN7LH89TUN4&t=819s>)
• [Buttons](<https://www.youtube.com/watch?v=e3EYsrasPms&t=362s>)
• [Select / Dropdown menu](<https://www.youtube.com/watch?v=n1hr0Idv4hQ>)
"""

[node]
keywords = ["node"]
content = """
**<:update:875645449523064852> NodeJS**
You need to update your node, [click here to download](<https://nodejs.org/en/download/>)
If you are on replit [click here](https://discord.com/channels/731532456724922459/766116919983079434/875648198859968522)
"""

